name: videotv_tv_test
description: VideoTV Android TV Test Version
publish_to: 'none'
version: 1.1.2+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.6
  webview_flutter: ^4.7.0
  path_provider: ^2.1.3
  firebase_core: ^2.31.0
  firebase_database: ^10.5.6
  fluttertoast: ^8.2.6
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  open_file: ^3.3.2
  audio_service: ^0.18.13
  just_audio: ^0.9.38
  rxdart: ^0.27.7
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/foreground.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png" 