name: videotv
description: A Flutter video list and player example
publish_to: 'none'
version: 1.5.251

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.6
  webview_flutter: ^4.7.0
  path_provider: ^2.1.1
  firebase_core: ^3.13.1
  firebase_database: ^11.3.6
  fluttertoast: ^8.2.12
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  open_file: ^3.5.10
  external_path: ^2.2.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
